repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json

      - id: end-of-file-fixer
      - id: trailing-whitespace

      - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        entry: ruff check
        args:
          - --select
          - I
          - --fix
      - id: ruff
        entry: ruff check
        args:
          - --fix
      - id: ruff-format
